name: nabdh_alyaman
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  awesome_dialog: ^3.0.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.8.4
  csc_picker: ^0.2.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  email_validator: ^2.1.17
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_datetime_picker: ^1.5.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.4
  fluttertoast: ^8.1.3
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.6
  hive: null
  hive_flutter: null
  http: ^0.13.5
  image_picker: ^0.8.6
  internet_connection_checker: ^1.0.0+1
  introduction_screen: ^3.1.4
  location: ^4.4.0
  lottie: ^2.2.0
  modal_progress_hud_nsn: ^0.3.0
  package_info_plus: ^3.0.3
  permission_handler: ^10.2.0
  share_plus: ^7.0.2
  url_launcher: ^6.1.7

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/nabdh square.png"

dev_dependencies:
  build_runner: null
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: null

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - data/country.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
