name: nabdh_alyaman
description: A blood donation app
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.5.1
  csc_picker: ^0.2.7
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  email_validator: ^3.0.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker_plus: ^2.2.0
  flutter_localization: ^0.2.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.16
  fluttertoast: ^8.2.8
  geolocator: ^13.0.2
  get_it: ^7.2.0
  google_maps_flutter: ^2.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  introduction_screen: ^3.1.14
  location: ^7.0.1
  lottie: ^3.2.0
  modal_progress_hud_nsn: ^0.5.1
  package_info_plus: ^8.1.1
  permission_handler: ^11.3.1
  share_plus: ^10.1.2
  url_launcher: ^6.3.1

flutter_icons:
  android: 'launcher_icon'
  ios: false
  image_path: 'assets/images/nabdh square.png'

dev_dependencies:
  build_runner: null
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: null

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - data/country.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
