// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnJYLcdijgKMd0FWAIB0Wsuo7SU4Ao5Gc',
    appId: '1:484743968286:web:afb2061ed9f74b0c41e00f',
    messagingSenderId: '484743968286',
    projectId: 'nabdh-alyaman',
    authDomain: 'nabdh-alyaman.firebaseapp.com',
    storageBucket: 'nabdh-alyaman.appspot.com',
    measurementId: 'G-VFLFQ0194S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8uZ5U0ioQToCHzZ-vqbJCh3FoldIYWAc',
    appId: '1:484743968286:android:e61b5634ec2fcaaa41e00f',
    messagingSenderId: '484743968286',
    projectId: 'nabdh-alyaman',
    storageBucket: 'nabdh-alyaman.appspot.com',
  );
}
